name: NBA Stats Scraper

on:
  schedule:
    - cron: '*/5 * * * *'  # ✅ Runs every 5 minutes (for testing)
    - cron: '15 1 * * 1-5'  # ✅ Runs at 5:20 PM CT (3:20 AM UTC) (First Half)
    - cron: '40 1 * * 1-5'  # ✅ Runs at 5:50 PM CT (3:50 AM UTC) (Second Half)
  workflow_dispatch:  # ✅ Allows manual trigger

jobs:
  scrape_data_first_half:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper (First Half)
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: python scraper.py first  # ✅ Corrected argument passing

  scrape_data_second_half:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper (Second Half)
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: python scraper.py second  # ✅ Corrected argument passing
