name: NBA Stats Scraper

on:
  schedule:
    - cron: '20 23 * * 1-5'  # ✅ Runs at 3 AM UTC (First Half)
    - cron: '50 23 * * 1-5'  # ✅ Runs at 4 AM UTC (Second Half)
  workflow_dispatch:  # ✅ Allows manual trigger

jobs:
  scrape_data_first_half:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper (First Half)
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: python scraper.py --batch first

  scrape_data_second_half:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper (Second Half)
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: python scraper.py --batch second
