name: NBA Stats Scraper

on:
  workflow_dispatch:  # ✅ Allows manual trigger
  schedule:
    - cron: '15 20 * * 1-5'  # ✅ Runs at 6 AM UTC, Monday-Friday

jobs:
  scrape_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4  # ✅ Updated to latest version
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}  # ✅ Securely load Google credentials
        run: python scraper.py
