name: Run Peak Projection

on:
  schedule:
    - cron: '0 10 * * 1-5'  # ✅ Runs at 10:00 AM UTC (5:00 AM CT)
  workflow_dispatch:  # ✅ Allows manual trigger

jobs:
  run_peak_projections:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Peak Projection Script
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: python peak.py
