name: Update NBA Stats Daily

on:
  schedule:
    - cron: "0 8 * * 1-5"  # Runs at 8 AM UTC, Monday to Friday

  workflow_dispatch:  # Allows manual execution
  
jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use a compatible Python version

      - name: Install Dependencies
        run: |
          pip install pandas gspread oauth2client tqdm nba_api

      - name: Run NBA Stats Script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python nba_update_script.py
